# Generated by Django 4.0.4 on 2022-05-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='defaultname', max_length=255),
            preserve_default=False,
        ),
    ]
